### ISSUE TITLE
Why STM?

### ISSUE THREAD

**Issue by danr** [SamuelSchlesinger/stm-incremental#1]
Hi, nice reading your code, I'm just wondering what part of STM is actually used. I cannot see any use of say `retry` or `orElse`. Phrasing it another way: could the code be written using IORefs or STRefs instead?

**Comment by SamuelSchlesinger** [comment]
Either `STM` or `ST` could have been used for this, but `STM` allows us to use these variables concurrently. I cannot think of a way that this could be written with `IORef`s without a complex locking mechanism or disallowing concurrency at all with a global lock, which is not what I want.

**Comment by danr** [comment]
I see! Thank you for the explanation :)
